### PR TITLE
fix it for u

### PR DESCRIPTION
**Pull request by KDot227**

### CODE REVIEW

**Comment by Sbee6119** [comment]
[Errno 13] Permission denied: 'tmp_P5yJWpiJAVjsDzDaXkBxXQ.py'
I cant find a fix online.

**Comment by KDot227** [comment]
Merge the pr bruh

**Comment by NotKatsu** [comment]
> Merge the pr bruh
He said in his Discord he won't merge pull requests which seems super stupid but whatever

**Comment by KDot227** [comment]
> > Merge the pr bruh
> 
> 
> 
> He said in his Discord he won't merge pull requests which seems super stupid but whatever
> 
> 

Ik cause I was the mf admin tryna fix all his stuff

**Comment by NotKatsu** [comment]
> > > Merge the pr bruh
> > 
> > 
> > He said in his Discord he won't merge pull requests which seems super stupid but whatever
> 
> Ik cause I was the mf admin tryna fix all his stuff

ahh yeah im just gonna help out on another project no point helping him if he wont accept it, I added a feature the community said they wanted and he refused it so whatever.

**Comment by KDot227** [comment]
> > > > Merge the pr bruh
> 
> > > 
> 
> > > 
> 
> > > He said in his Discord he won't merge pull requests which seems super stupid but whatever
> 
> > 
> 
> > Ik cause I was the mf admin tryna fix all his stuff
> 
> 
> 
> ahh yeah im just gonna help out on another project no point helping him if he wont accept it, I added a feature the community said they wanted and he refused it so whatever.

Fr + he sounds like a women 💀

**Comment by NotKatsu** [comment]
> > > > > Merge the pr bruh
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > He said in his Discord he won't merge pull requests which seems super stupid but whatever
> > 
> > 
> > > 
> > 
> > 
> > > Ik cause I was the mf admin tryna fix all his stuff
> > 
> > 
> > ahh yeah im just gonna help out on another project no point helping him if he wont accept it, I added a feature the community said they wanted and he refused it so whatever.
> 
> Fr + he sounds like a women 💀

Yeah just leave everything to him and his 9 year old roblox gang

**Comment by Vito223** [comment]
When i click build it tells me to install all the libraries can someone help?

**Pull request closed without merging**
