### PR TITLE
Update build.py

### PR DESCRIPTION
**Pull request by KDot227**
less detections

### CODE REVIEW

**Comment by dekrypted** [comment]
oh i forgot to do this lol, lemme push the latest verson of my builder which has that added xd

**Comment by dekrypted** [comment]
oh wait actually nevermind i remember why i remove this its cause bytecode encryption is gonna be deprecated soon

**Comment by KDot227** [comment]
> oh wait actually nevermind i remember why i removed this its cause bytecode encryption is gonna be deprecated soon

soon == not yet 

abuse it while u still can

**Comment by dekrypted** [comment]
nah compatibility > one less detection

**Comment by KDot227** [comment]
> nah compatibility > one less detection

LLLLLLLLLLL

**Pull request closed without merging**
